### ISSUE TITLE
Versioned images

### ISSUE THREAD

**Issue by daler** [conda-forge/docker-images#43]
Currently the images just have a "latest" tag, and over on bioconda we recently had builds failing due to changes in the `linux-anvil` image we weren't aware of. Pinning to a tagged image would help this sort of thing in the future. @jakirkham suggested git sha as tags, which for our purposes would be great

xref https://github.com/bioconda/bioconda-recipes/issues/3080#issuecomment-264225814

**Comment by zbeekman** [comment]
Same issue here. I'm happy to help contribute the fix, but someone needs to point me in the right direction on how the nightly updates happen. linux-anvil/comp7 is failing today but wasn't yesterday.

@isuruf any ideas?

**Comment by isuruf** [comment]
Why not use the digest? `docker pull condaforge/linux-anvil-comp7@sha256:cbc1e39aa69fbf623514b6409ea3d7c9980354c10136e85095aad20c402d3cdf` ?

**Comment by zbeekman** [comment]
@isuruf It seems I had the digest syntax mixed up. The dockerhub tags page makes it look like you don't need the @sha256 bit. 

Also, I guess tags based on the git SHA won't help because nothing in this repository changed overnight, but the new nightly build (condaforge/linux-anvil-comp7@sha256:cbc1e39aa69fbf623514b6409ea3d7c9980354c10136e85095aad20c402d3cdf) is broken for me:

https://github.com/ParaToolsInc/CommanderConda/runs/700052426?check_suite_focus=true#step:9:730 then it fails with:

```
fetching: conda-4.8.3-py37hc8dfbb8_1.tar.bz2
Checking for duplicate files ...
Traceback (most recent call last):
  File "/opt/conda/bin/constructor", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/constructor/main.py", line 244, in main
    dry_run=args.dry_run, conda_exe=args.conda_exe)
  File "/opt/conda/lib/python3.7/site-packages/constructor/main.py", line 119, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/opt/conda/lib/python3.7/site-packages/constructor/fcp.py", line 245, in main
    ignore_duplicate_files, verbose, dry_run
  File "/opt/conda/lib/python3.7/site-packages/constructor/fcp.py", line 215, in _main
    pc_recs, platform, ignore_duplicate_files
  File "/opt/conda/lib/python3.7/site-packages/constructor/fcp.py", line 126, in check_duplicates_files
    getsize(join(extracted_package_dir, short_path)))
  File "/opt/conda/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/.conda/constructor/linux-64/sysroot_linux-64-2.12.2-h3a0023d_0/x86_64-conda-linux-gnu/sysroot/lib/libgomp.so'
```

It was working with yesterday's image: @sha256:9bef6c41d7add4c09327280582da0e53905a2f9ea1ba151e751c

However, after further debugging this seems to be an issue with something else; possibly a transient problem due to GitHub's degraded status. Things are working again with the latest docker image.

Sorry for the noise, and thanks for chiming in!

**Comment by hajapy** [comment]
I would like to use versioned images as well, specifically for the miniforge image. I don’t see how to follow the suggestion to use sha256 as the tag - docker hub only shows latest. I also don’t understand the objection... it seems to me we just need to set the tag in .travis.yml. Why is that controversial?

**Comment by isuruf** [comment]
PRs welcome. Note that a PR should have the following properties.
1. Both tags are used. `latest` and the version tag.
2. There's a check that the version tag and the conda version is the same.
3. The version tag is automatically updated so that we don't have to bump it every time.

**Comment by xhochy** [comment]
@isuruf @wolfv  Would you be ok with moving the `miniforge` image to the miniforge repository so that we get new builds of that directly on releases? That would make keeping them in sync much simpler. If that's ok, I would be happy to put in a PR for that.

**Comment by wolfv** [comment]
No problem from my side.

We will also have an official micromamba docker starting tomorrow :)

**Comment by xhochy** [comment]
Moved the builds over to https://github.com/conda-forge/miniforge-images and now we also have versioned images.
