### ISSUE TITLE
chmod in entrypoint takes ages

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/docker-images#63]
On my local machine, the `chown` on the conda folder ([here](https://github.com/conda-forge/docker-images/blob/master/linux-anvil/entrypoint#L14)) takes about 8 min to complete. Probably this has not been an issue before, but only occurs now after the meltdown patches? I guess this might also lead to considerable slowdowns in CI. I wonder if there is a way to avoid the chown?

**Comment by mbargull** [comment]
Looking at another [discussion](https://github.com/tootsuite/mastodon/issues/3194) on a similar topic, the slowdowns are likely most prominent when the `overlay2` storage driver is used.

**Comment by jakirkham** [comment]
FWIW it looks like CircleCI also uses `overlay2`. Definitely have seen some slowdown due to this personally, but not to the tune of 8mins. Probably closer to seconds. Though haven't been hit bad enough personally to need to measure. Wonder if there is something more going on in your case. Perhaps a slow OS FS?

Would be open to other options. The main challenge is that we need to make sure the UID of the user in the container matches that of the user outside the container. Otherwise we basically can't do anything with the mounted directories. Given how the feedstocks are setup, this includes everything from updating packages, doing the build, etc.

**Comment by sdvillal** [comment]
We also use a linux-anvil inspired image for our internal CI, and since our I/O budget is a bit tight, this was slightly annoying. What we do is simply to chown the conda dir like:

```
# lucky group gets permissions to write in the conda dir
RUN groupadd -g 32767 lucky
RUN chgrp -R lucky /opt/conda && chmod -R g=u /opt/conda
```

And then add the unprivileged user to the "lucky" group each time we spin a container.

**Comment by jakirkham** [comment]
@gqmelo, thoughts?

**Comment by jakirkham** [comment]
We could also look at using [`fixuid`]( https://github.com/boxboat/fixuid ). Basically a tool intended to solve this problem.

**Comment by gqmelo** [comment]
But it would face the same problem. From the README:

> changes all file permissions for old dockeruser:dockergroup to

**Comment by jakirkham** [comment]
> `RUN groupadd -g 32767 lucky`

Is this number meaningful or is it arbitrary, @sdvillal?

**Comment by sdvillal** [comment]
Arbitrary.

**Comment by sdvillal** [comment]
#68 tackles this
