### ISSUE TITLE
why is make necessary

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/docker-images#78]
https://github.com/conda-forge/docker-images/blob/bd432d78d1949d12df1a8f0ec59b61627fcfcb0c/linux-anvil-comp7/Dockerfile#L18

Is make necessary in the docker image?

It seems we can always add it to the conda dependencies right?

**Comment by hmaarrfk** [comment]
I think this is hiding a few unlisted dependencies on make :/

**Comment by hmaarrfk** [comment]
I'm just going to document the packages that need updating here, if you want to remove make from the dependency, we will have to issue udpates to them:

- expat-feedstock
- libtool-feedstock
- ncurses-feedstock
- rhash-feedstock

**Comment by jakirkham** [comment]
This has been around since we moved the Docker image over here. So nearly 3 years ago! 😲

We didn't have a package for `make` at the time. In fact, we added `make` nearly 1 year later.

Anyways people have been adding `make` during the rebuild and encouraging it on new recipes. I'm sure we can remove it once we've gotten the remain things to include it as a requirement.

There's probably a few other things like this we should revisit.

xref: https://github.com/conda-forge/docker-images/pull/5

**Comment by hmaarrfk** [comment]
Got it. Thanks. I just figured I would document whatever I had to change to get things to compile.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/conda-forge/docker-images/pull/94 ) to try dropping `make` from the Docker images.

**Comment by jakirkham** [comment]
As noted in [this discussion]( https://github.com/conda-forge/docker-images/pull/94#discussion_r296798403 ), `make` comes preincluded with CentOS 6 x86_64 images. So dropping `make` from this list doesn't stop it from being there.
