### ISSUE TITLE
Large image

### ISSUE THREAD

**Issue by epruesse** [conda-forge/docker-images#82]
The layer created here has ~1.4GB size:

https://github.com/conda-forge/docker-images/blob/6152d61e4afdc63816b4865a72bf17fbb9ced17c/linux-anvil-comp7/Dockerfile#L31-L48

**Comment by isuruf** [comment]
Since we are using `conda-forge::gcc_linux-64` instead of `conda-forge/label/gcc7::gcc_linux-64` there is no benefit from caching at all

**Comment by scopatz** [comment]
Yeah, I am not sure how much can realistically be done about this.

**Comment by jakirkham** [comment]
> Since we are using `conda-forge::gcc_linux-64` instead of `conda-forge/label/gcc7::gcc_linux-64` there is no benefit from caching at all

These were added before the compiler migration; so, naturally they are out-of-date. 😄 Thanks @mariusvniekerk for updating them.

**Comment by jakirkham** [comment]
> Yeah, I am not sure how much can realistically be done about this.

Here are some thoughts.

We could drop this layer and just spend CI time downloading the compilers. It's worth noting though that they were added because people preferred to have them cached.

We could choose to remove some things that are less frequently used like Fortran. This won't eliminate the full cost of this layer, but maybe this ends up being a notable improvement.

It could be that there is some overlapping content between many layers that would be eliminated by merging them using [multi-stage builds]( https://medium.com/@tonistiigi/advanced-multi-stage-build-patterns-6f741b852fae ). That said, we already do a pretty heavy amount of cleaning after each layer to avoid unneeded remnants. Would not be surprised if the savings here is small.

Do you have other thoughts @epruesse?

**Comment by jakirkham** [comment]
If we want to make a notable dent here, it's probably worth looking at [multistage builds]( https://docs.docker.com/develop/develop-images/multistage-build/ ). The first stage could be doing what is necessary to install Miniconda. The second stage could simply reuse the Miniconda install (without anything else) and proceed from there.

**Comment by epruesse** [comment]
That's pretty simple actually. I'm using it for our bot here: https://github.com/bioconda/bioconda-utils/blob/master/app/Dockerfile.web

**Comment by jakirkham** [comment]
I tried the experimental `--squash` option to `docker build` recently. That seemed to work pretty nicely. Also this achieves the best we could hope to get from multistage builds without having to fiddle with the Dockerfiles. That cuts out 0.71GB from the `condaforge/linux-anvil-comp7` image based on my tests locally. Have submitted PR ( https://github.com/conda-forge/docker-images/pull/99 ) to apply the same change to our Travis CI builds used for deployment here.

**Comment by epruesse** [comment]
:rocket:
